/**
 * reporter.js — Terminal and Markdown/JSON output.
 * Handles rendering of check results in all output formats.
 */

import {
  header,
  divider,
  summaryLine,
  statusIcon,
  statusLabel,
  checkName,
  checkMessage,
  fixHint,
  detailLine
} from './formatter.js'

/**
 * Print a full terminal report to stdout.
 * @param {object[]} results
 * @param {object} summary
 * @param {object} [opts]
 */
export async function printTerminal(results, summary, opts = {}) {
  const { version = '1.0.0' } = opts
  const lines = []

  lines.push(await header(version))

  const fixHints = []

  for (const result of results) {
    const icon = await statusIcon(result.status)
    const label = await statusLabel(result.status)
    const name = await checkName(result.name ?? result.key ?? '')
    const msg = await checkMessage(result.message ?? '')

    lines.push(`  ${icon}  ${name}  ${msg}  ${label}`)

    if (result.details?.length > 0) {
      for (const detail of result.details) {
        lines.push(await detailLine(detail))
      }
    }

    if (result.fix) {
      fixHints.push(result.fix)
    }
  }

  lines.push('')
  lines.push(await divider())
  lines.push(await summaryLine(summary))
  lines.push(await divider())

  if (fixHints.length > 0) {
    lines.push('')
    for (const hint of fixHints) {
      lines.push(await fixHint(hint))
    }
  }

  lines.push('')

  process.stdout.write(lines.join('\n') + '\n')
}

/**
 * Print a JSON report to stdout.
 * @param {object[]} results
 * @param {object} summary
 * @param {object} config
 */
export function printJson(results, summary, config = {}) {
  const output = {
    version: '1.0.0',
    timestamp: new Date().toISOString(),
    summary,
    results: results.map(r => ({
      key: r.key,
      name: r.name,
      status: r.status,
      message: r.message,
      details: r.details ?? [],
      fix: r.fix ?? null
    })),
    config: config._source ? { source: config._source } : {}
  }
  process.stdout.write(JSON.stringify(output, null, 2) + '\n')
}

/**
 * Generate a Markdown report (for GitHub PR comments, CI artifacts, etc.).
 * @param {object[]} results
 * @param {object} summary
 * @returns {string}
 */
export function generateMarkdown(results, summary) {
  const STATUS_MD = {
    pass: ':white_check_mark:',
    fail: ':x:',
    warn: ':warning:',
    skip: ':white_circle:',
    error: ':bangbang:'
  }

  const rows = results.map(r => {
    const icon = STATUS_MD[r.status] ?? ':question:'
    const name = r.name ?? r.key ?? ''
    const msg = r.message ?? ''
    const status = (r.status ?? '').toUpperCase()
    return `| ${icon} | **${name}** | ${msg} | ${status} |`
  })

  const fixSection = results
    .filter(r => r.fix)
    .map(r => `- **${r.name}**: ${r.fix}`)

  const lines = [
    '## PR Guard Report',
    '',
    `| | Check | Details | Status |`,
    `|---|---|---|---|`,
    ...rows,
    '',
    `**Result:** ${summary.passed} passed, ${summary.failed} failed, ${summary.skipped} skipped`
  ]

  if (fixSection.length > 0) {
    lines.push('', '### Issues to fix', '', ...fixSection)
  }

  lines.push('', '---', '*Generated by [PR Guard](https://github.com/NickCirv/pr-guard)*')

  return lines.join('\n')
}

/**
 * Set the process exit code based on results and strict mode.
 * @param {object} summary
 * @param {boolean} strict — if true, warnings also cause exit 1
 */
export function setExitCode(summary, strict = false) {
  const hasFailures = summary.failed > 0 || summary.errored > 0
  const hasWarnings = summary.warned > 0

  if (hasFailures || (strict && hasWarnings)) {
    process.exitCode = 1
  } else {
    process.exitCode = 0
  }
}
